[versions]
gradle-custom-user-data = "1.9"
gradle-enterprise = "3.12.4"
# Version for foojay should be also synced with version in repo/gradle-settings-conventions/settings.gradle.kts
gradle-toolchains-foojay-resolver = "0.4.0"
kotlinx-serialization = "1.5.0"

[libraries]
gradle-customUserData-gradlePlugin = { module = "com.gradle:common-custom-user-data-gradle-plugin", version.ref = "gradle-custom-user-data" }
gradle-enterprise-gradlePlugin = { module = "com.gradle:gradle-enterprise-gradle-plugin", version.ref = "gradle-enterprise" }
gradle-toolchainsFoojayResolver-gradlePlugin = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "gradle-toolchains-foojay-resolver" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
